<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class-bindings [
  <!ELEMENT class-bindings (datamanager-binding, session-binding)>
  <!ELEMENT datamanager-binding (datamanager+)>
  <!ELEMENT datamanager (manager-name, manager-class)>
  <!ELEMENT manager-name        (#PCDATA)>
  <!ELEMENT manager-class       (#PCDATA)>
  <!ELEMENT session-binding (session-class)>
  <!ELEMENT session-class       (#PCDATA)>

]>

<!-- ================================================================== -->
<!-- Elitecore Technologies Ltd.                                        -->
<!-- Please do not edit this file                                       -->
<!-- ================================================================== -->
 <class-bindings>

    <datamanager-binding>
       
	    <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.core.system.staff.StaffDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.core.system.staff.HStaffDataManager</manager-class>
        </datamanager>
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.core.system.systemparameter.SystemParameterDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.core.system.systemparameter.HSystemParameterDataManager</manager-class>
        </datamanager>
       
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.core.system.profilemanagement.ProfileDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.core.system.profilemanagement.HProfileDataManager</manager-class>
        </datamanager>
		<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.core.system.accessgroup.AccessGroupDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.core.system.accessgroup.HAccessGroupDataManager</manager-class>
        </datamanager>  
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.systemaudit.SystemAuditDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.systemaudit.HSystemAuditDataManager</manager-class>
        </datamanager>
         <!--  datasource database  datamanager  binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.datasource.database.DatabaseDSDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.datasource.database.HDatabaseDSDataManager</manager-class>
        </datamanager>
        <!--  datasource LDAP  datamanager  binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.datasource.ldap.LDAPDSDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.datasource.ldap.HLDAPDatasourceDataManager</manager-class>
        </datamanager>
        

        <!-- session manager datamanager  binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.sessionmanager.SessionManagerDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.sessionmanager.HSessionManagerDataManager</manager-class>
        </datamanager>
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.sessionmanager.ASMDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.sessionmanager.HASMDataManager</manager-class>
        </datamanager>
        
        
        <!-- digest config datamanager  binding  -->
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.digestconf.DigestConfDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.digestconf.HDigestConfDataManager</manager-class>
        </datamanager>

        <!-- client profile binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.clientprofile.ClientProfileDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.clientprofile.HClientProfileDataManager</manager-class>
        </datamanager>
        
        <!-- external system related binding  -->
       	<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.externalsystem.ExternalSystemInterfaceDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.externalsystem.HExternalSystemInterfaceDataManager</manager-class>
        </datamanager>
        
         <!-- driver related binding  -->
       	<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.drivers.DriverDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.drivers.HDriverDataManager</manager-class>
        </datamanager>
        
        
        <!--database subscriber profile related binding  -->
       	<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.drivers.subscriberprofile.database.DatabaseSubscriberProfileDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.drivers.subscriberprofile.database.HDatabaseSubscriberProfileDataManager</manager-class>
        </datamanager>
        
        
		<!-- Service related binding  -->
       	<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.service.ServiceDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.service.HServiceDataManager</manager-class>
        </datamanager>
        
        <!-- Service Policy Related binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servicepolicy.auth.AuthServicePoilcyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servicepolicy.auth.HAuthServicePoilcyDataManager</manager-class>
        </datamanager>
        
        
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servicepolicy.acct.AcctServicePoilcyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servicepolicy.acct.HAcctServicePoilcyDataManager</manager-class>
        </datamanager>
        
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servicepolicy.dynauth.DynAuthServicePoilcyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servicepolicy.dynauth.HDynAuthServicePoilcyDataManager</manager-class>
        </datamanager>
        
        <!--server-->
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.server.NetServerDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.server.HServerDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.service.NetServiceDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.service.HServiceDataManager</manager-class>
        </datamanager>
        
        <!-- Resource Manager -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.rm.ippool.IPPoolDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.rm.ippool.HIPPoolDataManager</manager-class>
        </datamanager>
        
        <!-- EAP Config Manager -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.eap.EAPConfigDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.eap.HEAPConfigDataManager</manager-class>
        </datamanager>
 
        <!-- Alert Listener binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.alert.AlertListenerDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.alert.HAlertListenerDataManager</manager-class>
        </datamanager>
        <!-- Grace Policy binding  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermgr.gracepolicy.GracePolicyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.gracepolicy.HGracePolicyDataManager</manager-class>
        </datamanager>
        
        
        <!-- Radius binding -->
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.clientprofile.ClientProfileDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.clientprofile.HClientProfileDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.dictionary.DictionaryDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.dictionary.HDictionaryDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.policies.accesspolicy.AccessPolicyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.policies.accesspolicy.HAccessPolicyDataManager</manager-class>
        </datamanager>
        
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.policies.radiuspolicy.RadiusPolicyDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.policies.radiuspolicy.HRadiusPolicyDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.radtest.RadiusTestDataManager</manager-name>        	
			<manager-class>com.elitecore.elitesm.hibernate.radius.radtest.HRadiusTestDataManager</manager-class>
        </datamanager>
               
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.bwlist.BWListDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.radius.bwlist.HBWListBLManager</manager-class>
        </datamanager>
        
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.rm.concurrentloginpolicy.ConcurrentLoginPolicyDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.rm.concurrentloginpolicy.HConcurrentLoginPolicyDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.wsconfig.WebServiceConfigDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.wsconfig.HWebServiceConfigDataManager</manager-class>
        </datamanager>
		
		<datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.dictionary.DictionaryDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.dictionary.HDictionaryDataManager</manager-class>
        </datamanager>
        
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servicepolicy.diameter.naspolicy.DiameterNASPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servicepolicy.diameter.naspolicy.HDiameterNASPolicyDataManager</manager-class>
        </datamanager>

         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servicepolicy.diameter.creditcontrolpolicy.CreditControlPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servicepolicy.diameter.creditcontrolpolicy.HCreditControlPolicyDataManager</manager-class>
        </datamanager>

		<datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servicepolicy.diameter.eappolicy.EAPPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servicepolicy.diameter.eappolicy.HEAPPolicyDataManager</manager-class>
        </datamanager>
        
         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.drivers.DiameterDriverDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.drivers.HDiameterDriverDataManager</manager-class>
        </datamanager>

	   <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.transmapconf.TranslationMappingConfDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.transmapconf.HTranslationMappingConfDataManager</manager-class>
        </datamanager>
        
         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.copypacket.CopyPacketTransMapConfDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.copypacket.HCopyPacketTransMappingDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.diameterpolicy.DiameterPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.diameterpolicy.HDiameterPolicyDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servicepolicy.rm.cgpolicy.CGPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servicepolicy.rm.cgpolicy.HCGPolicyDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.reports.userstat.UserStatisticsDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.reports.userstat.HUserStatisticsDataManager</manager-class>
        </datamanager>

        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.routingconf.DiameterRoutingConfDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.routingconf.HDiameterRoutingConfDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.diameterpeerprofile.DiameterPeerProfileDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.diameterpeerprofile.HDiameterPeerProfileDataManager</manager-class>
        </datamanager>
         
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.diameterpeer.DiameterPeerDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.diameterpeer.HDiameterPeerDataManager</manager-class>
        </datamanager>        
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.routingentry.DiameterRoutingEntryDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.routingentry.HDiameterRoutingEntryDataManager</manager-class>
        </datamanager>
        
        <!-- Generic datamanager  binding  -->
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.core.base.GenericDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.core.base.HGenericDataManager</manager-class>
        </datamanager>
        
         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.certificate.ServerCertificateDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.certificate.HServerCertificateDataManager</manager-class>
        </datamanager>
        
         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.certificate.TrustedCertificateDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.certificate.HTrustedCertificateDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.servermgr.certificate.CrlCertificateDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.servermgr.certificate.HCrlCertificateDataManager</manager-class>
        </datamanager>
       
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.dashboard.DashboardDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.dashboard.HDashboardDataManager</manager-class>
        </datamanager>
       
         <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.core.system.systemparameter.PasswordPolicyDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.core.system.systemparameter.HPasswordPolicyDataManager</manager-class>
        </datamanager>
        
         <!-- Priority Table   -->
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.prioritytable.PriorityTableConfDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.prioritytable.HPriorityTableConfDataManager</manager-class>
        </datamanager>
        
        <!-- Dashboard   -->
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.dashboard.DashboardDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.dashboard.HDashboardDataManager</manager-class>
        </datamanager>
        
        <!-- Dashboard Chart -->
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.dashboard.ChartDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.dashboard.HChartDataManager</manager-class>
        </datamanager>

 		<!-- Audit History   -->
		<datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.history.HistoryDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.history.HHistoryDataManager</manager-class>
        </datamanager>
        
        <!-- Diameter Session Manager   -->
        <datamanager>
           <manager-name>com.elitecore.elitesm.datamanager.diameter.sessionmanager.DiameterSessionManagerDataManager</manager-name>
           <manager-class>com.elitecore.elitesm.hibernate.diameter.sessionmanager.HDiameterSessionManagerDataManager</manager-class>
        </datamanager>
        
        <!-- Radius Service Policy -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servicepolicy.radiusservicepolicy.RadiusServicePolicyDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.servicepolicy.radiusservicepolicy.HRadiusServicePoilcyDataManager</manager-class>
        </datamanager>

		<!-- IMSI Based Routing Table Manager -->
		<datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.diameter.imsibasedroutingtable.IMSIBasedRoutingTableDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.diameter.imsibasedroutingtable.HIMSIBasedRoutingTableDataManager</manager-class>
        </datamanager>
        
        <!-- MSISDN Based Routing Table Manager -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.diameter.msisdnbasedroutingtable.MSISDNBasedRoutingTableDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.diameter.msisdnbasedroutingtable.HMSISDNIBasedRoutingTableDataManager</manager-class>
        </datamanager>
        
        <!-- Radius Policy Group -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.radiuspolicygroup.RadiusPolicyGroupDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.radius.radiuspolicygroup.HRadiusPolicyGroupDataManager</manager-class>
        </datamanager>
        
        <!-- Diameter Policy Group -->
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.diameter.diameterpolicygroup.DiameterPolicyGroupDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.diameter.diameterpolicygroup.HDiameterPolicyGroupDataManager</manager-class>
        </datamanager>
        
        <!-- Diameter Concurrency -->
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.diameter.diameterconcurrency.DiameterConcurrencyDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.diameter.diameterconcurrency.HDiameterConcurrencyDataManager</manager-class>
        </datamanager>
        
         <!-- Plugin  -->
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servermanager.plugins.PluginDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.servermgr.plugins.HPluginDataManager</manager-class>
        </datamanager>
        
        <!-- TGPP AAA POLICY -->
         <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.servicepolicy.diameter.tgppaaapolicy.TGPPAAAPolicyDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.servicepolicy.diameter.tgppaaapolicy.HTGPPAAAPolicyDataManager</manager-class>
         </datamanager>
        
         <!-- Diameter Peer Group -->
          <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.diameter.diameterpeergroup.DiameterPeerGroupDataManager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.diameter.diameterpeergroup.HDiameterPeerGroupDataManager</manager-class>
         </datamanager> 
        
        <datamanager>
        	<manager-name>com.elitecore.elitesm.datamanager.radius.radiusesigroup.RadiusESIGroupDatamanager</manager-name>
        	<manager-class>com.elitecore.elitesm.hibernate.radius.radiusesigroup.HRadiusESIGroupDataManager</manager-class>
         </datamanager>
          
        <!-- SM License -->
        <datamanager>
			<manager-name>com.elitecore.elitesm.datamanager.core.system.license.SMLicenseDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.core.system.license.HSMLicenseDataManager</manager-class>
		</datamanager>
		
		<!-- IN-MEMORY DATA GRID -->
        <datamanager>
			<manager-name>com.elitecore.elitesm.datamanager.inmemorydatagrid.InMemoryDataGridDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.inmemorydatagrid.HInMemoryDataGridDataManager</manager-class>
		</datamanager>


		<!-- System Audit Relation -->
		<datamanager>
			<manager-name>com.elitecore.elitesm.datamanager.systemaudit.relation.SystemAuditRelationDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.systemaudit.relation.HSystemAuditRelationDataManager</manager-class>
		</datamanager>

	    <!-- Script -->
        <datamanager>
			<manager-name>com.elitecore.elitesm.datamanager.servermanager.script.ScriptDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.servermgr.script.HScriptDataManager</manager-class>
		</datamanager>
	
	    <!-- Database Properties -->
		 <datamanager>
			<manager-name>com.elitecore.elitesm.datamanager.core.system.databaseproperties.DatabasePropertiesDataManager</manager-name>
			<manager-class>com.elitecore.elitesm.hibernate.core.system.databaseproperties.HDatabasePropertiesDataManager</manager-class>
		</datamanager>

        <!-- Correlated Session -->
        <datamanager>
            <manager-name>com.elitecore.elitesm.datamanager.radius.correlatedradius.CorrelatedRadiusDataManager</manager-name>
            <manager-class>com.elitecore.elitesm.hibernate.radius.correlatedradius.HCorrelatedRadiusDataManager</manager-class>
        </datamanager>
		
    </datamanager-binding>
    <session-binding> 
        <session-class>com.elitecore.elitesm.hibernate.core.system.util.HibernateDataSession</session-class>
    </session-binding>
</class-bindings>
