<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE class-bindings [
  <!ELEMENT class-bindings (datamanager-binding, session-binding)>
  <!ELEMENT datamanager-binding (datamanager+)>
  <!ELEMENT datamanager (manager-name, manager-class)>
  <!ELEMENT manager-name        (#PCDATA)>
  <!ELEMENT manager-class       (#PCDATA)>
  <!ELEMENT session-binding (session-class)>
  <!ELEMENT session-class       (#PCDATA)>

]>

<!-- ================================================================== -->
<!-- Elitecore Technologies Ltd.                                        -->
<!-- Please do not edit this file                                       -->
<!-- ================================================================== -->
 <class-bindings>

    <datamanager-binding>
       
	    <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.core.system.staff.StaffDataManager</manager-name>
        	<manager-class>com.elitecore.netvertexsm.hibernate.core.system.staff.HStaffDataManager</manager-class>
        </datamanager>
        <datamanager>
           <manager-name>com.elitecore.netvertexsm.datamanager.core.system.systemparameter.SystemParameterDataManager</manager-name>
           <manager-class>com.elitecore.netvertexsm.hibernate.core.system.systemparameter.HSystemParameterDataManager</manager-class>
        </datamanager>
        
        <datamanager>
           <manager-name>com.elitecore.netvertexsm.datamanager.core.system.systemparameter.PasswordPolicyDataManager</manager-name>
           <manager-class>com.elitecore.netvertexsm.hibernate.core.system.systemparameter.HPasswordPolicyDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.core.system.profilemanagement.ProfileDataManager</manager-name>
        	<manager-class>com.elitecore.netvertexsm.hibernate.core.system.profilemanagement.HProfileDataManager</manager-class>
        </datamanager>
		<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.core.system.accessgroup.AccessGroupDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.core.system.accessgroup.HAccessGroupDataManager</manager-class>
        </datamanager>  
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.systemaudit.SystemAuditDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.systemaudit.HSystemAuditDataManager</manager-class>
        </datamanager>
       
   		<!-- Gateway related binding -->
   		
   		<datamanager>
   			<manager-name>com.elitecore.netvertexsm.datamanager.gateway.GatewayDataManager</manager-name>
   			<manager-class>com.elitecore.netvertexsm.hibernate.gateway.HGatewayDataManager</manager-class>
   		</datamanager>
   		<datamanager>
   			<manager-name>com.elitecore.netvertexsm.datamanager.gateway.attrmapping.PacketMapDataManager</manager-name>
   			<manager-class>com.elitecore.netvertexsm.hibernate.gateway.attrmapping.HPacketMapDataManager</manager-class>
   		</datamanager>
   		<datamanager>
   			<manager-name>com.elitecore.netvertexsm.datamanager.gateway.pccrulemapping.RuleMappingDataManager</manager-name>
   			<manager-class>com.elitecore.netvertexsm.hibernate.gateway.pccrulemapping.HRuleMappingDataManager</manager-class>
   		</datamanager>
   		
        <!-- BI Module related binding -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.bitemplate.BITemplateDataManager</manager-name>
        	<manager-class>com.elitecore.netvertexsm.hibernate.bitemplate.HBITemplateDataManager</manager-class>
        </datamanager>
   		
   		<!-- ESI RADIUS related binding -->
   		<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.datasource.esiradius.EsiRadiusDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.datasource.esiradius.HEsiRadiusDataManager</manager-class>
        </datamanager>   		
   		
   		<!-- Datasource database related binding -->
   		<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.datasource.database.DatabaseDSDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.datasource.database.HDatabaseDSDataManager</manager-class>
        </datamanager>
        
        <!-- Datasource LDAP related binding -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.datasource.ldap.LDAPDSDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.datasource.ldap.HLDAPDatasourceDataManager</manager-class>
        </datamanager>

		<!-- Session Manager related binding -->
		<datamanager>
			<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.sessionmgr.SessionDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.sessionmgr.HSessionDataManager</manager-class>
		</datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.sessionmgr.ASMDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.sessionmgr.HASMDataManager</manager-class>
        </datamanager>

        <!-- Driver related binding -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.drivers.DriverDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.drivers.HDriverDataManager</manager-class>
        </datamanager>
        
        <!-- Driver related binding -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.spinterface.SPInterfaceDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.spinterface.HSPInterfaceDataManager</manager-class>
        </datamanager>
        
   		
		<!-- Service related binding  -->
       	<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.service.ServiceDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.service.HServiceDataManager</manager-class>
        </datamanager>
       
        <!-- server -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.server.NetServerDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.server.HServerDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.service.NetServiceDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.service.HServiceDataManager</manager-class>
        </datamanager>
        
        <!-- PCRF Service Policy related binding -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servicepolicy.ServicePolicyDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servicepolicy.HServicePolicyDataManager</manager-class>
        </datamanager>
        
      	 <!-- Alert Listener binding  -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.alert.AlertListenerDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.alert.HAlertListenerDataManager</manager-class>
        </datamanager>
      
        <!-- Radius Dictionary -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.dictionary.radius.RadiusDictionaryDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.dictionary.radius.HRadiusDictionaryDataManager</manager-class>
        </datamanager>
        
         <!-- Diameter Dictionary -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.dictionary.diameter.DiameterDictionaryDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.dictionary.diameter.HDiameterDictionaryDataManager</manager-class>
        </datamanager>
        
        <!--  Device Management -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.devicemgmt.DeviceMgmtDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.devicemgmt.HDeviceMgmtDataManager</manager-class>
        </datamanager>
		
		<!--  MCC-MNC Management -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.RoutingTable.network.NetworkDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.RoutingTable.network.HNetworkDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.RoutingTable.mccmncgroup.MCCMNCGroupDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.RoutingTable.mccmncgroup.HMCCMNCGroupDataManager</manager-class>
        </datamanager>

        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.customizedmenu.CustomizedMenuDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.CustomizedMenu.HCustomizedMenuDataManager</manager-class>
        </datamanager>

		<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.RoutingTable.mccmncroutingtable.MCCMNCRoutingTableDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.RoutingTable.mccmncroutingTable.HMCCMNCRoutingTableDataManager</manager-class>
        </datamanager>
        <!-- location manager -->
  		<datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.locationconfig.area.AreaDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.locationconfig.area.HAreaDataManager</manager-class>
        </datamanager>
        
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.locationconfig.region.RegionDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.locationconfig.region.HRegionDataManager</manager-class>
        </datamanager>
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.locationconfig.city.CityDataManager</manager-name>
			<manager-class>com.elitecore.netvertexsm.hibernate.locationconfig.city.HCityDataManager</manager-class>
        </datamanager>
        
     	<!-- Certificate Manager binding  -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.certificate.ServerCertificateDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.certificate.HServerCertificateDataManager</manager-class>
        </datamanager>

        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.certificate.CrlCertificateDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.certificate.HCrlCertificateDataManager</manager-class>
        </datamanager>        

        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.certificate.TrustedCertificateDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.certificate.HTrustedCertificateDataManager</manager-class>
        </datamanager>        

        <datamanager>
           <manager-name>com.elitecore.netvertexsm.datamanager.core.base.GenericDataManager</manager-name>
           <manager-class>com.elitecore.netvertexsm.hibernate.core.base.HGenericDataManager</manager-class>
        </datamanager>
        
        
        <!--  SPR  -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.spr.SPRDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.spr.HSPRDataManager</manager-class>
        </datamanager>
        
        <!--  DDF  -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.servermgr.spr.ddf.DDFDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.servermgr.spr.ddf.HDDFDataManager</manager-class>
        </datamanager>
        
        <!--  Group Data -->
        <datamanager>
        	<manager-name>com.elitecore.netvertexsm.datamanager.core.system.group.GroupDataManager</manager-name>        	
			<manager-class>com.elitecore.netvertexsm.hibernate.core.system.group.HGroupDataManager</manager-class>
        </datamanager>
        
         <datamanager>
            <manager-name>com.elitecore.netvertexsm.datamanager.servergroup.ServerInstanceGroupDataManager</manager-name>
            <manager-class>com.elitecore.netvertexsm.hibernate.servergroup.HServerInstnaceGroupDataManager</manager-class>
        </datamanager>
        
    </datamanager-binding>
    <session-binding> 
        <session-class>com.elitecore.netvertexsm.hibernate.core.system.util.HibernateDataSession</session-class>
    </session-binding>
</class-bindings>
